name: tachiyuki_modules
description: Source modules for the Tachiyuki app.
version: 1.0.0
repository: https://github.com/Zerolmntrix/kagayaku-modules

environment:
  sdk: ^3.0.6

dependencies:
  web_scraper: ^0.1.4

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
